### ISSUE TITLE
continuous testing?

### ISSUE THREAD

**Issue by bc** [gertvv/hitandrun#10]
I really enjoy using this package, and am integrating the primary functions into biomechanical research. Have you considered using a continuous testing service, such as travis-ci? That way we can be notified if a dependency breaks, or if a new change affects other functions unexpectedly.

Brian

**Comment by gertvv** [comment]
I wasn't aware this was so easy to set up now for R packages. Thanks for the prompt, I've added a Travis build badge to the README now.
